### ISSUE TITLE
[MAUI][ANDROID] Tabs become unresponsive when applying AppThemeBinding (Light/Dark)

### ISSUE THREAD

**Issue by sk1llsh0t** [roubachof/Sharpnado.Tabs#127] opened 2024-10-10 12:42 UTC
Platform (please complete the following information):

OS: [Android]
Device: Tab Active 3 [Android API Level 31]
Sdk Version: Min: 30 Target: 34
MAUI: [NET 8.0][8.0.91]

I have added light/dark AppThemeBinding to my app's style.xaml sheet to handle when the system switches between modes. With the tabhostview, I'm noticing that when the theme switches, the tabs become unresponsive.
 
Would you have any insights on why this might occur? Not at this time

Maybe similar to these 2 issues but not sure. (https://github.com/roubachof/Sharpnado.Tabs/issues/120) (https://github.com/roubachof/Sharpnado.Tabs/issues/84)

To Reproduce
1) Create an app with the Tabs control
2) In the Resources/Styles/Styles.xaml, add styling for the various tab components with AppThemeBindings for light and dark modes
3) Run the app. while you are on the page with the tabs, tap around to make sure it is working. 
4) Then, from the notification tray, change the theme from light to dark or vice versa.
5) Dismiss the notification tray after the theme has switched so you are back in the app.
6) At this point, the tabs are disabled/unresponsive

One other observation, if i have a main page and navigate to a detail page (with the tab control), then switch the dark/light mode, come back to the app, the tabs are disabled. i can navigate back to the main page and then go back to the detail page and it is working again.

Styles used in my Style.xaml file: (of course change the color StaticResources to match your colors)
```
 <Style TargetType="sho:TabHostView" x:Key="TabHostView">
        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource LightBackground02}, Dark={StaticResource DarkBackground02}}" />
        <Setter Property="SegmentedOutlineColor" Value="{AppThemeBinding Light={StaticResource Gray950}, Dark={StaticResource Gray200}}" />
        <Setter Property="CornerRadius" Value="10" />
        <Setter Property="TabType" Value="Fixed" />
        <Setter Property="IsSegmented" Value="True" />
        <Setter Property="Orientation" Value="Horizontal" />
        <Setter Property="SegmentedHasSeparator" Value="True" />
    </Style>
    
    <Style TargetType="sho:UnderlinedTabItem" x:Key="UnderlinedTabItem">
        <Setter Property="SelectedTabColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource PrimaryLight}}" />
        <Setter Property="UnselectedLabelColor" Value="{AppThemeBinding Light={StaticResource LightSecondaryText}, Dark={StaticResource DarkSecondaryText}}" />
    </Style>
    
    <Style TargetType="sho:BadgeView" x:Key="BadgeView">
        <Setter Property="Background" Value="{StaticResource Secondary}"></Setter>
    </Style>
```

Expected Behavior: Tabs can be clicked and views load as expected.

**Comment by janusw** [comment] 2024-10-10 16:04
> I have added light/dark AppThemeBinding to my app's style.xaml sheet to handle when the system switches between modes. With the tabhostview, I'm noticing that when the theme switches, the tabs become unresponsive.

I can confirm this ...

> Maybe similar to these 2 issues but not sure. (#120) (#84)

... and yes, I think all of them are due to the same root cause.

**Comment by roubachof** [comment] 2024-10-18 14:37
should be fixed by v3.1.0, please re-open if it doesn't.

**Closed by roubachof** 2024-10-18 14:37 UTC
Labels: bug

**Comment by sk1llsh0t** [comment] 2024-10-22 20:09
It appears that the tabs are functioning now when switching between dark and light modes. However, it looks like the colors are no longer loading for the selected mode. Whatever the color was when the tabview initially loads is the color it has throughout its life until the page is closed and reopened.

I'm using Tabs 3.1.1

**Comment by sk1llsh0t** [comment] 2024-10-22 20:39
The original issue is fixed. Now i notice the text colors for selected and unselected tabs aren't switching when the dark/light mode changes. The background color changes and the segmentedoutlinecolor changes. Something isn't working right with the text colors though when switching.
