### ISSUE TITLE
[MAUI] [Android] Sharpnado tabs become unusable in combination with MAUI Shell Tabbar

### ISSUE THREAD

**Issue by janusw** [roubachof/Sharpnado.Tabs#120] opened 2024-09-25 13:35 UTC
**Platform (please complete the following information):**
 - OS: Android
 - Device: Samsung Galaxy S21
 - Sdk version: Android SDK 34
 - MAUI: 8.0.72

**Describe the bug**
I see strange behavior of a Sharpnado tab bar inside a MAUI application with Shell Tabbar. In certain situations the Sharpnado tabs become unusable and don't react any more.
I'm not actually sure if this is a bug in the MAUI framework itself, or in Sharpnado.Tabs (could be both, I guess).

**To Reproduce**
1. Download the sample project from https://github.com/janusw/maui-samples/tree/Sharpnado.Tabs_bug/8.0/Navigation/ShellTabBarSample (this is a modified variant of the `ShellTabBarSample` in my fork of the `maui-samples`).
2. Build and run it.
3. On the shell tab 'One', click the button ("Click me").
4. A secondary page with a Sharpnado tab bar opens. The tabs have no content in this sample (for simplicity), but switching them works fine.
5. Switch to the shell tab 'Two'.
6. Switch back to 'One'.
7. The Sharpnado tabs are not usable any more. They don't react to tapping.

**Comment by janusw** [comment] 2024-09-25 16:12
I verified that the problem occurs also with the latest MAUI version 8.0.90 and down to 8.0.7.

**Comment by janusw** [comment] 2024-09-25 16:12
I verified that the problem occurs also with the latest MAUI version 8.0.90 and down to 8.0.7.

**Comment by roubachof** [comment] 2024-09-27 08:33
seems like a good first issue for the new contributor of the repo ;)

**Comment by makazeu** [comment] 2024-10-06 03:18
I can confirm this issue repro in my scenario

**Comment by janusw** [comment] 2024-10-08 08:20
> I verified that the problem occurs also with the latest MAUI version 8.0.90 and down to 8.0.7.

For completeness: It also happens with .NET 7 (and with 8.081, which was released in the meantime).

By now I suspect that it's rather a bug in Sharpnado.Tabs (and not in the MAUI framework).

**Comment by janusw** [comment] 2024-10-08 09:26
I now also set up a reproducer directly in my fork of the Sharpnado.Tabs repo, so that one can debug it directly (together with the lib, and not via the nupkg):

https://github.com/janusw/Sharpnado.Tabs/commits/MauiShellSample/

From the log output and some debugging, I see that `TabHostView.OnTabItemTapped` is triggered correctly as long as one stays on the same shell tab. After switching shell tabs, it is not triggered any more, but I currently have no idea why.

@roubachof Do you have any ideas how to debug this? Or some suggestions what to try?

**Comment by janusw** [comment] 2024-10-08 09:47
> should be linked to this: #84 maybe?

Quite probable that this is related. Thanks for the pointer!

https://github.com/roubachof/Sharpnado.Tabs/issues/84#issuecomment-2165192578 mentions a solution concerning `OnHandlerChanged`. I did some debugging of the TabHostView events and found that:
* the `Unloaded` event is triggered when navigating away from the shell tab that contains the Sharpnado tabs
* the `Loaded` and `HandlerChanged` events are triggered when navigating back to the shell tab that contains the Sharpnado tabs

**Comment by janusw** [comment] 2024-10-08 11:36
I tried the following in the OnHandlerChanged method of the TabHostView:

```
        protected override void OnHandlerChanged()
        {
            base.OnHandlerChanged();
            InternalLogger.Debug(Tag, () => $"HandlerChanged!");
            foreach (var tabItem in Tabs)
            {
                AddTapCommand(tabItem);
            }
        }
```

However, this does not seem to fix the problem. Any comments?

https://github.com/roubachof/Sharpnado.Tabs/issues/84#issuecomment-2165192578 says:
> Fixed by reregistering the effect in the OnHandlerChanged override.

Am I doing the wrong thing here? Or maybe it is a different issue, after all ...?!?

**Comment by roubachof** [comment] 2024-10-18 10:57
well it's not linked to #84 since I cannot reproduce the issue with .net8

**Comment by roubachof** [comment] 2024-10-18 14:37
should be fixed by v3.1.0, please re-open if it doesn't.

**Closed by roubachof** 2024-10-18 14:37 UTC
Labels: bug

**Comment by janusw** [comment] 2024-10-18 15:10
Well, yes, I can confirm that v3.1.0 indeed fixes this problem on Android. Thanks! 👍 

BUT: It looks like this release completely breaks iOS. The tabs do not react to tapping at all on iOS (observed with my own application, have not checked the sample yet). 😱

**Comment by roubachof** [comment] 2024-10-18 15:42
CAn you set UseMauiTapGesture to true on the TabHostView ?

**Comment by janusw** [comment] 2024-10-18 16:16
> CAn you set UseMauiTapGesture to true on the TabHostView ?

Yes, indeed this makes the tab on iOS react again. Maybe it should be the default then (on iOS)? Or are there any downsides?

**Comment by roubachof** [comment] 2024-10-21 09:15
I just tested on the sample and it's working fine : 

https://github.com/user-attachments/assets/0bb263cf-396e-4fa7-bc34-242d0acdd9f3

**Comment by janusw** [comment] 2024-10-21 20:13
> I just tested on the sample and it's working fine :

Yes, it's working in principle (i.e. the tabs react to touching), but it's missing the touch effects on the main toolbar (where you set `UseMauiTapGesture`). This is the same problem as in my PR #126, which you rejected.

**Comment by roubachof** [comment] 2024-10-22 07:32
I don't understand you said:

> It looks like this release completely breaks iOS. The tabs do not react to tapping at all on iOS (observed with my own application, have not checked the sample yet). 😱

But it does react at tapping, you also have the color feedback.
Do you say that you don't have the color feedback on the bottombar ?
If yes your PR didn't add color effect, on the contrary it removed it for all tab items.

**Comment by janusw** [comment] 2024-10-22 08:26
> I don't understand...

Ok, let's get this straight ....

> > It looks like this release completely breaks iOS. The tabs do not react to tapping at all on iOS (observed with my own application, have not checked the sample yet). 😱

This statement concerned my own app: The tabs on iOS did not react at all. This is fixed by using `UseMauiTapGesture`.

> But it does react at tapping, you also have the color feedback. Do you say that you don't have the color feedback on the bottombar ?

Now you're talking about the `MauiSample` app. For this one, the tabs on iOS seems to react, even without `UseMauiTapGesture` (you added it for some of the TabHostViews there, e.g. on the MainPage, but not all of them).

However, the color effect when tapping seems to be removed by `UseMauiTapGesture`, e.g. on the MainPage. In your screen recording it is also missing for the main tab bar (but it was there before version 3.1.0).

Btw, I also checked that the tabs are reacting in the MauiShellSample. I'm not sure why it did not work in my case.

> If yes your PR didn't add color effect, on the contrary it removed it for all tab items.

Right, I did not mean to say that my PR is better than what you did. 😉 

The other way around: Your implementation has the same problem as my naive PR. 😆 (but at least you added a property to switch it).

Would be nice to have one solution that fully works everywhere instead of having workarounds for specific cases.

IIUC, you may need to get rid of the old effects anyway for .NET 9 (in MAUI they we're only kept for compatibility with Xamarin, but it seems like .NET 9 finally removes this compatibility) ...

**Comment by roubachof** [comment] 2024-10-22 08:53
I am so lost right now :)
Let's stop talking on a close issue and please open new issues if something is not working as expexted

**Comment by janusw** [comment] 2024-10-22 09:08
> I am so lost right now :) Let's stop talking on a closed issue and please open new issues if something is not working as expected

Alright 👍 (#130 seems related).

But you can confirm that the touch effect on the sample's main tab bar is missing right now? That's a "regression" in the sample, in a way.

**Comment by roubachof** [comment] 2024-10-22 09:11
When you are using UseMauiGesture, it uses maui vanilla gesturen which has no touch effect or tap sound
