### ISSUE TITLE
[MAUI/Xamarin.Forms/Both] supported  .NET7？

### ISSUE THREAD

**Issue by simphonydeveloper** [roubachof/Sharpnado.Tabs#75] opened 2023-03-01 01:09 UTC
I cannot use it after installing with nuget.

**Comment by roubachof** [comment] 2023-03-01 08:01
The maui nuget target .net6 which can be used in .net7

**Comment by simphonydeveloper** [comment] 2023-03-01 08:05
Change the TargetFrameworks of the project.

**Comment by simphonydeveloper** [comment] 2023-03-01 08:05
I have a test today and found that it cannot be used on. NET 7.

**Comment by roubachof** [comment] 2023-03-01 08:41
which platform ?

**Comment by simphonydeveloper** [comment] 2023-03-01 08:42
Andriod

**Comment by roubachof** [comment] 2023-03-01 08:52
just tested it on net7.0-android, it works as expected
![image](https://user-images.githubusercontent.com/596903/222090230-9f01b3ec-8c35-462f-8c6e-c53117a9913f.png)

**Comment by simphonydeveloper** [comment] 2023-03-01 08:55
What do you set after installing the nuget package?
I can run your example.
There is another problem. I run the sample and then slide the contents of the tab with my finger. It will not jump.

**Comment by roubachof** [comment] 2023-03-01 09:16
sorry this is 2 differents issues, and the second one is a duplicate of an existing enhancement

**Closed by roubachof** 2023-03-01 09:16 UTC
Labels: not reproducible

**Comment by simphonydeveloper** [comment] 2023-03-01 10:13
Thank you for your reply and look forward to your new features.
